Suffix bug fix
CriminalInjuriesCompensationAuthority/ajv-formats-mobile-uk pull request #2
Opened 2021-04-20 11:23 UTC by armoj

Fixes [this](https://github.com/ruimarinho/google-libphonenumber/issues/279) issue.

2021-04-23 10:22 UTC, sinclairs requested changes

2021-04-23 10:22 UTC, sinclairs commented on lib/mobilePhoneNumberValidator.js
> +            const formatted = phoneUtil.format(number);
Can this be removed? I reckon it's redundant and the tests are passing without it

2021-04-23 10:22 UTC, sinclairs commented on lib/mobilePhoneNumberValidator.js
> +            if (input.replace(/[\s-]/g, '').endsWith(formatted.replace(/[\s-]/g, ''))) {
Can this be removed? I reckon it's redundant and the tests are passing without it

2021-04-26 16:50 UTC, BarryPiccinni approved these changes

2021-04-26 16:59 UTC, merged